### ISSUE TITLE
Set source on play

### ISSUE THREAD

**Issue by bjarteskogoy** [aesculus/denonavpcontrol#14]
It would be nice if the plugin could reset the input source when you play something. Maybe the receiver has been used for something else in the meantime.

If the repo could be set up with the source not only as a zip I could submit a PR.

**Comment by aesculus** [comment]
It supports the Quick Select (1-3). That will reset the source if you turn the player off/on.

The source is in the zip file.

**Comment by bjarteskogoy** [comment]
I have one receiver which supports quick select and an older Marantz which does not. It would be nice if we could get the change "wagner-ch" did, as a pull request.

A lot of the time the receiver has been used for TV-audio or something else in between playing music. It would be nice if pressing play re-selected the input source, select input or quick select, instead of having to turn the squeezebox off and on to get the correct input.

**Comment by aesculus** [comment]
I understand why the input may need to be reset and can consider other than the Quick Select.

But I am not sure why this needs to be done at every play.  Why is it not appropriate to do this only when the player is turned on?

**Comment by bjarteskogoy** [comment]
I have already implemented the input select, https://github.com/bjarteskogoy/denonavpcontrol

But I have not looked into making sure the receiver is on when you start playing.

**Comment by aesculus** [comment]
We are going to look at adding this in the next release after 3.0 which is pending any day now.

**Comment by aesculus** [comment]
After reviewing this request we felt that it was too unique and would not be utilized by enough users to justify the effort. We were also worried that it could cause confusion and problems that we would have to deal with.

Since you have a working solution we felt it was best to have you continue doing what you do. Note that version 4.0 will probably be the last for awhile so if you concentrate on updating your process for that version you should be safe.
