### ISSUE TITLE
Mystery

### ISSUE THREAD

**Issue by tboneco** [aesculus/denonavpcontrol#20]
I have an old Denon 3808, a very old but great AVP that just keeps working.  It does not have airplay nor HDMI CEC, so this app is perfect for me.  I run two zones and decided to use PiCorePlayer for zone 2.  The PCP is connected to 3808 via optical cable.  I then loaded AirPlay Bridge plug-in as it allows my kids to easily play Spotify through my other Logitechs as they show as AirPlay devices.  Here’s the mystery.

Today, I was on the deck and started SirusXM on my iPad.  Normally I use iPeng to play music.  I started ALT station and then clicked Devices/AirPlay in the app.  I see DECK listed as that’s my PCP, the plug-in enables it as an AirPlay device.  I selected the PCP and then thought, oh wait the Denon won’t turn on so went to go turn it on and music started playing!  Somehow the Denon turned on to zone2 but my 3808 does not support AirPlay as it’s the original version that was never firmware updated to support AirPlay.  I tested this twice from cold state and it works.  If I pause the music on the SiriusXM app, the Denon shuts off…. Click play and it turns on again but then turns off after a few seconds.  If I switch the SiriusXM app device back to iPad, start the stream, and then switch the device back to the PCP, Denon turns on and music streams just fine.  Going to try other apps like Spotify and Amazon music but cannot figure out how the Denon is turning on!

**Comment by aesculus** [comment]
It does sound interesting, but I suspect the logs will tell us what is happening.

If you could go into the LMS Settings > Advanced > Logging and scroll the the DenonAVP plugin and set the logging to Debug and select Apply.

Then repeat your scenarios as you described. Then go back in the LMS Settings and copy the log here. Also I will need you to mock up the log with time stamps on when you did the steps in the scenario.

This way I will know what action caused each of the events.

There may be something to fix or at least you will know what actions are causing these "mysteries".

**Comment by tboneco** [comment]
Attached is the log.  I don't understand the log enough to mark exactly when my actions occurred, but I only did two actions: select device in app and pause music in app.  However, I put comments in the log as requested.

[SiriusXM 3808 Test.log](https://github.com/aesculus/denonavpcontrol/files/9035023/SiriusXM.3808.Test.log)

**Comment by aesculus** [comment]
The plugin is monitoring LMS output to the Denon. You have directed that from Sirius via the PCP (which is now an airplay device) to the Denon.

It's good that you logged both the Denon plugin and the Airplay plugin, because we can see the relationship.

So any output to DECK is going to be looked at by the Denon plugin. For an example:

You caused the Airplay plugin to pause
[22-07-03 09:02:35.6100] Plugins::ShairTunes2W::AIRPLAY::canDoAction (27) Action=pause

The Denon plugin caught that and went into it's pause routine:
[22-07-03 09:02:35.6135] Plugins::DenonAvpControl::Plugin::commandCallback (1927) *** DenonAvpControl: commandCallback() p0: pause
[22-07-03 09:02:35.6138] Plugins::DenonAvpControl::Plugin::commandCallback (1928) *** DenonAvpControl: commandCallback() p1: 
[22-07-03 09:02:35.6141] Plugins::DenonAvpControl::Plugin::commandCallback (1950) *** DenonAvpControl: commandCallback() Player: Deck
[22-07-03 09:02:35.6145] Plugins::DenonAvpControl::Plugin::commandCallback (1958) *** DenonAvpControl: power request1: Slim::Control::Request=HASH(0x7fc634b5d420) 
[22-07-03 09:02:35.6161] Plugins::DenonAvpControl::Plugin::commandCallback (1927) *** DenonAvpControl: commandCallback() p0: playlist
[22-07-03 09:02:35.6164] Plugins::DenonAvpControl::Plugin::commandCallback (1928) *** DenonAvpControl: commandCallback() p1: stop
[22-07-03 09:02:35.6168] Plugins::DenonAvpControl::Plugin::commandCallback (1950) *** DenonAvpControl: commandCallback() Player: Deck

But now it gets weird. In some logic changes we have in the plugin we now turn on the Denon (because it was off) so it can deal with the situation.

So let us look into this a bit more. But basically the Denon plugin is working as designed since it's not just for iPeng, but is actually getting into the stream for everything you send to your Denon via that LMS "player", in this case the airplay plugin.

**Comment by tboneco** [comment]
Ah, makes sense!  Glad I understand it better now.  One correction I have is that the plug-in I use is ShairTunes2W, not AirPlay Bridge but same developer.

**Comment by aesculus** [comment]
Super. While our predominant model is/was real LMS players, and soon Material Skin, we have not purposefully tried to exclude any other setup.

So after using it this way, if you come up with some suggestions on how to improve it in this mode, please feel free to post another issue and we can try to address it. If it's simple or will aid in the other use cases, we will certainly entertain doing it.
