### ISSUE TITLE
Idea: Set other input source on exit before turning off

### ISSUE THREAD

**Issue by ChrisS85** [aesculus/denonavpcontrol#30]
For use cases where the AVR is used for other tasks (like TV or PC connections), it would be nice if it could automatically switch back to a "default" channel when turning off a player.

Atleast my Denon AVR X1000 doesn't seem to have an option to always start with one preselected input as far as I can tell.

**Comment by SamInPgh** [comment]
This functionality would be outside the scope of the plugin. The Denon AVRs generally default to the last active input when powering on. Two ways around this are:

1. Use the HDMI Control (CEC) function of the AVR to automatically turn on and switch to an input when the device connected to that input is turned on. This requires support for CEC on the desired input device.
2. Define a Quick Select button that turns the AVR on and switches to the desired input upon invoking it, and use that button rather than the Power button when turning the AVR on.

**Comment by SamInPgh** [comment]
Closing this pending further feedback from the requester.

**Comment by SamInPgh** [comment]
It sounds like you have a grip on what would need to be done but I really don't have the bandwidth to take this issue any further right now. Sorry.

What I will say, though, is that the foundational principle of your argument --- "...if I turn a device on and then immediately turn it off again, I would expect to be back in the same situation as before without any side effects" does not really apply here because the plugin is not just turning the AVR on. It is also switching it to the input specified in the plugin's "Input Select Option" setup menu field --- either implicitly via the Quick Select option or explicitly via the "AVR Input Source" option. If, however, you really would like to bypass setting the input source and simply "turn the device on", you can do so by typing the literal "NONE" into the "AVR Input Source" field and hitting "Save Settings". Then, if you turn the AVR on via the plugin and immediately turn it off, as in your usage example, it will indeed "be back in the same situation as before without any side effects." Once you manually change the input  to your Lyrion source, however, you're on your own. 😉

Triviality is, of course, relative and I did not mean to imply that the changes would be that huge of a task --- especially with the aid of an AI assistant. It's just not something I have either the time or inclination to do right now.

Good luck!
